import type { EarningsAnalysis } from "@/lib/types";

const NVDA: EarningsAnalysis = {
  profile: {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Semiconductors",
    marketCap: "$3.42T",
    price: 142.86,
    change: 2.18,
    changePct: 1.55,
    earningsDate: "2026-05-28",
    earningsQuarter: "Q1 FY2027",
  },
  priceTarget: { current: 142.86, average: 168.5, high: 220, low: 110, analysts: 62, rating: "Buy" },
  reaction: {
    oneDay: 3.8,
    fiveDay: 6.4,
    sinceEarnings: 9.1,
    reasonSummary:
      "Data center revenue beat consensus by 8% and Blackwell shipments ramped faster than guided. Guidance for next quarter came in above the Street.",
    marketReaction:
      "Broad enthusiasm — AI infrastructure demand thesis reinforced. Semis basket rallied in sympathy.",
  },
  callSummary:
    "NVIDIA reported another record quarter driven by Blackwell platform demand across hyperscalers, sovereign AI, and enterprise. Management framed AI infrastructure buildout as multi-year, called out supply headroom improving, and pointed to networking and software as growing attach opportunities.",
  sentimentScore: 72,
  themes: [
    { title: "Blackwell ramp acceleration", explanation: "Blackwell shipments ramped faster than the prior guide with meaningful revenue contribution this quarter.", evidence: "\"Blackwell revenue exceeded our expectations, and we expect it to grow significantly in Q2.\"", sentiment: "positive", status: "new" },
    { title: "Sovereign AI demand", explanation: "Nation-state AI programs are becoming a durable revenue category.", evidence: "Management called out multi-billion sovereign AI pipeline across EU, Middle East, and APAC.", sentiment: "positive", status: "recurring" },
    { title: "Networking attach (Spectrum-X, NVLink)", explanation: "Networking is becoming a bigger share of platform revenue.", evidence: "Spectrum-X annualized run rate cited above $12B.", sentiment: "positive", status: "recurring" },
    { title: "Enterprise / agentic AI monetization", explanation: "Enterprise workloads and agentic AI called out as next leg of demand.", evidence: "Multiple Fortune 500 deployments referenced.", sentiment: "positive", status: "new" },
    { title: "China export controls", explanation: "China data center revenue remains muted; H20 alternatives in play but limited visibility.", evidence: "Q&A: multiple analysts pressed on China contribution.", sentiment: "negative", status: "recurring" },
    { title: "Gross margin normalization", explanation: "GM stepping down modestly as Blackwell mix ramps, then reaccelerating in H2.", evidence: "\"Gross margin will dip to mid-70s before recovering.\"", sentiment: "neutral", status: "recurring" },
    { title: "Gaming stabilization", explanation: "Gaming segment returning to seasonal growth after prior softness.", evidence: "Gaming revenue up sequentially.", sentiment: "positive", status: "fading" },
  ],
  narrative: {
    coreStory: "NVIDIA is the platform layer of the AI industrial revolution — full stack from silicon to networking to software.",
    growthDrivers: ["Blackwell + Rubin roadmap", "Sovereign AI", "Enterprise agentic workloads", "Networking (Spectrum-X, NVLink)"],
    profitabilityStory: "Gross margin dips near-term on Blackwell ramp then re-accelerates to mid-70s as yields improve and networking mix grows.",
    strategicPriorities: ["Annual product cadence", "Software + services monetization", "Ecosystem lock-in via CUDA"],
    confidenceLevel: "High",
    toneChange: "Slightly more measured on China; more confident on sovereign and enterprise pipeline.",
  },
  qa: {
    topConcerns: ["Sustainability of hyperscaler capex", "China revenue trajectory", "Gross margin path"],
    pushedTopics: ["Blackwell yield", "Sovereign AI revenue timing", "Competitive dynamics vs custom ASICs"],
    repeatedQuestions: ["When does gross margin bottom?", "Blackwell vs Rubin transition risk?"],
    strongestAnswers: ["Multi-year infrastructure demand framing", "Networking attach math"],
    weakestAnswers: ["China revenue visibility", "Specific ASP disclosure by product"],
  },
  bull: {
    mainArgument: "Multi-year AI infrastructure buildout with NVIDIA as the default platform.",
    points: ["Blackwell ramp exceeding plan", "Sovereign AI pipeline > $30B", "Networking as second leg", "Software revenue compounding"],
    catalysts: ["Rubin product launch cadence", "Enterprise agentic AI adoption", "New hyperscaler capex cycles"],
    analystView: "62 analysts; average PT $168.50 implies ~18% upside.",
  },
  bear: {
    mainArgument: "Hyperscaler capex is cyclical and could digest, while custom ASICs erode NVIDIA share.",
    points: ["Concentration risk in top 4 customers", "China revenue impaired", "GM pressure from Blackwell ramp", "Elevated inventory across ecosystem"],
    risks: ["Capex digestion cycle", "Regulatory / export controls", "Competition from TPU / MTIA / Trainium"],
    analystView: "Bears cite PT floor near $110 assuming capex normalization in FY28.",
  },
  qoq: {
    increasing: ["Sovereign AI mentions", "Networking attach", "Agentic AI"],
    decreasing: ["Hopper", "Gaming as % of narrative"],
    newThemes: ["Enterprise agentic AI monetization"],
    droppedThemes: ["Crypto/mining exposure commentary"],
    repeatedPhrases: ["\"Full stack\"", "\"Multi-year\"", "\"Accelerated computing\""],
    kpiChanges: "DC revenue +18% QoQ; networking annualized run rate +40% YoY.",
    guidanceChanges: "Revenue guide raised; GM guide slightly lowered near-term.",
    analystSentimentChange: "Slightly more constructive; PTs raised across 22 sell-side shops.",
  },
  metrics: [
    { label: "Revenue", value: "$41.2B", change: "+62% YoY", sentiment: "positive" },
    { label: "Data Center Revenue", value: "$32.8B", change: "+81% YoY", sentiment: "positive" },
    { label: "Non-GAAP EPS", value: "$0.87", change: "+58% YoY", sentiment: "positive" },
    { label: "Non-GAAP Gross Margin", value: "74.6%", change: "-180bps QoQ", sentiment: "neutral" },
    { label: "Operating Cash Flow", value: "$21.4B", change: "+72% YoY", sentiment: "positive" },
    { label: "Next-Q Revenue Guide", value: "$45.0B ± 2%", change: "+ vs consensus", sentiment: "positive" },
  ],
  quotes: [
    { speaker: "Jensen Huang", role: "CEO", topic: "Blackwell", quote: "Blackwell is the fastest ramp in our history.", whyItMatters: "Signals sustained revenue acceleration into H2." },
    { speaker: "Colette Kress", role: "CFO", topic: "Gross margin", quote: "Gross margin will dip to the mid-70s before recovering.", whyItMatters: "Sets clear GM floor for the model." },
    { speaker: "Jensen Huang", role: "CEO", topic: "Sovereign AI", quote: "Every nation will build sovereign AI infrastructure.", whyItMatters: "Frames sovereign as a durable, multi-year TAM." },
    { speaker: "Vivek Arya", role: "BofA Analyst", topic: "China", quote: "Can you quantify the China data center opportunity under current rules?", whyItMatters: "Highlights ongoing analyst concern about China visibility." },
    { speaker: "Jensen Huang", role: "CEO", topic: "Agentic AI", quote: "Agentic AI is a trillion-dollar opportunity ahead of us.", whyItMatters: "Extends narrative beyond training into inference and enterprise." },
  ],
  watchlist: [
    { category: "Metric", item: "Blackwell revenue mix by end of Q3" },
    { category: "Metric", item: "Non-GAAP gross margin trough & recovery slope" },
    { category: "Theme", item: "Sovereign AI contract signings" },
    { category: "Risk", item: "Hyperscaler capex commentary from MSFT/GOOG/META/AMZN" },
    { category: "Question", item: "China DC revenue trajectory under updated export controls" },
    { category: "Catalyst", item: "Rubin platform reveal cadence" },
  ],
};

const AAPL: EarningsAnalysis = {
  profile: {
    ticker: "AAPL",
    name: "Apple Inc.",
    sector: "Consumer Electronics",
    marketCap: "$3.18T",
    price: 208.42,
    change: -1.14,
    changePct: -0.54,
    earningsDate: "2026-05-01",
    earningsQuarter: "Q2 FY2026",
  },
  priceTarget: { current: 208.42, average: 224.1, high: 275, low: 165, analysts: 44, rating: "Buy" },
  reaction: {
    oneDay: -1.8,
    fiveDay: -0.4,
    sinceEarnings: 1.2,
    reasonSummary:
      "iPhone revenue in line but Services growth decelerated modestly. Apple Intelligence rollout timing questions weighed on sentiment.",
    marketReaction: "Muted — bulls point to installed base leverage, bears highlight China softness.",
  },
  callSummary:
    "Apple posted in-line iPhone revenue with Services growth of 12%. Management emphasized Apple Intelligence device attach, Vision Pro developer momentum, and record installed base of 2.3B active devices.",
  sentimentScore: 28,
  themes: [
    { title: "Apple Intelligence attach", explanation: "AI features driving device upgrade intent, especially for iPhone 16 and later.", evidence: "\"Markets where Apple Intelligence is available show stronger iPhone growth.\"", sentiment: "positive", status: "recurring" },
    { title: "Services deceleration", explanation: "Services grew 12% vs 14% prior — modest deceleration but still high margin.", evidence: "Services revenue $26.3B.", sentiment: "neutral", status: "recurring" },
    { title: "Greater China weakness", explanation: "China revenue -6% YoY on competitive pressure from domestic OEMs.", evidence: "Q&A: multiple analyst questions on China.", sentiment: "negative", status: "recurring" },
    { title: "Installed base leverage", explanation: "2.3B active devices; monetization runway across Services.", evidence: "Record active installed base cited.", sentiment: "positive", status: "recurring" },
    { title: "Vision Pro developer momentum", explanation: "Developer ecosystem for spatial computing growing but small commercial impact.", evidence: "\"Over 2,500 apps built for visionOS.\"", sentiment: "neutral", status: "fading" },
    { title: "Gross margin resilience", explanation: "Product GM steady; Services GM at 74%.", evidence: "Total GM 46.6%.", sentiment: "positive", status: "recurring" },
  ],
  narrative: {
    coreStory: "Installed base + Services flywheel, with Apple Intelligence as the next upgrade catalyst.",
    growthDrivers: ["Apple Intelligence-driven upgrades", "Services monetization", "Wearables ecosystem"],
    profitabilityStory: "Services mix drives sustained GM expansion; buybacks compound EPS.",
    strategicPriorities: ["On-device AI", "Ecosystem depth", "India expansion"],
    confidenceLevel: "Medium",
    toneChange: "More cautious on China; more confident on AI-driven upgrade cycle.",
  },
  qa: {
    topConcerns: ["China trajectory", "Apple Intelligence rollout pace", "Services growth durability"],
    pushedTopics: ["iPhone 17 cycle expectations", "Regulatory (DOJ, EU DMA)", "AI capex"],
    repeatedQuestions: ["When does China stabilize?", "How material is AI to unit growth?"],
    strongestAnswers: ["Installed base durability", "Services margin structure"],
    weakestAnswers: ["Specific AI attach metrics", "China unit forecast"],
  },
  bull: {
    mainArgument: "AI-driven iPhone upgrade cycle + Services compounding = multi-year EPS growth.",
    points: ["2.3B installed base", "Services @ 74% GM", "Buyback cadence", "India ramp"],
    catalysts: ["iPhone 17 launch", "Full Apple Intelligence rollout", "Vision Pro 2"],
    analystView: "44 analysts; average PT $224 implies ~7.5% upside.",
  },
  bear: {
    mainArgument: "iPhone units are flat, China is losing share, and AI has yet to prove a unit catalyst.",
    points: ["China -6% YoY", "iPhone units flattish", "Regulatory Services pressure", "Rich multiple"],
    risks: ["DOJ Google search deal", "EU DMA revenue impact", "China competitive intensity"],
    analystView: "Bear PT $165 assumes Services growth to high-single digits.",
  },
  qoq: {
    increasing: ["Apple Intelligence mentions", "India commentary"],
    decreasing: ["Vision Pro references", "China optimism"],
    newThemes: ["On-device model rollout cadence"],
    droppedThemes: ["Specific Vision Pro unit color"],
    repeatedPhrases: ["\"Record installed base\"", "\"Ecosystem\""],
    kpiChanges: "Services growth 14% → 12%; China -3% → -6%.",
    guidanceChanges: "Guidance ranges tightened; no explicit revenue guide (per policy).",
    analystSentimentChange: "Slightly more mixed; PT dispersion widened.",
  },
  metrics: [
    { label: "Revenue", value: "$95.4B", change: "+4% YoY", sentiment: "positive" },
    { label: "iPhone Revenue", value: "$46.8B", change: "+1% YoY", sentiment: "neutral" },
    { label: "Services Revenue", value: "$26.3B", change: "+12% YoY", sentiment: "positive" },
    { label: "Greater China Revenue", value: "$16.4B", change: "-6% YoY", sentiment: "negative" },
    { label: "Gross Margin", value: "46.6%", change: "+40bps YoY", sentiment: "positive" },
    { label: "Diluted EPS", value: "$1.65", change: "+8% YoY", sentiment: "positive" },
  ],
  quotes: [
    { speaker: "Tim Cook", role: "CEO", topic: "AI", quote: "Apple Intelligence markets are seeing stronger iPhone growth.", whyItMatters: "Signals AI as a real upgrade catalyst." },
    { speaker: "Luca Maestri", role: "CFO", topic: "Services", quote: "Services set an all-time record.", whyItMatters: "Confirms flywheel durability despite deceleration." },
    { speaker: "Tim Cook", role: "CEO", topic: "China", quote: "We remain optimistic about our long-term opportunity in China.", whyItMatters: "Muted framing vs previous quarters." },
    { speaker: "Erik Woodring", role: "MS Analyst", topic: "Upgrade cycle", quote: "Can you quantify the AI-driven upgrade lift?", whyItMatters: "Highlights the Street's central unknown." },
  ],
  watchlist: [
    { category: "Metric", item: "iPhone unit growth in AI-available markets" },
    { category: "Metric", item: "Services growth rate stabilization" },
    { category: "Theme", item: "Apple Intelligence rollout in China / EU" },
    { category: "Risk", item: "DOJ Google search ruling impact on Services" },
    { category: "Catalyst", item: "iPhone 17 launch reception" },
  ],
};

const GENI: EarningsAnalysis = {
  profile: {
    ticker: "GENI",
    name: "Genius Sports Limited",
    sector: "Sports Tech / Data",
    marketCap: "$2.1B",
    price: 9.42,
    change: 0.28,
    changePct: 3.06,
    earningsDate: "2026-05-13",
    earningsQuarter: "Q1 2026",
  },
  priceTarget: { current: 9.42, average: 12.6, high: 16, low: 8, analysts: 9, rating: "Buy" },
  reaction: {
    oneDay: 6.2,
    fiveDay: 8.9,
    sinceEarnings: 11.4,
    reasonSummary:
      "Revenue beat and raised full-year guidance driven by NFL product uptake and BetVision adoption. Adjusted EBITDA margin expanded 400bps.",
    marketReaction: "Positive — bulls point to operating leverage; short interest cover contributed to move.",
  },
  callSummary:
    "Genius Sports reported 24% revenue growth, raised FY guidance, and highlighted strong momentum in the NFL partnership and BetVision. Management emphasized structural operating leverage and free cash flow inflection.",
  sentimentScore: 66,
  themes: [
    { title: "NFL product monetization", explanation: "NFL data + BetVision driving sportsbook ARPU expansion in the US.", evidence: "\"BetVision now integrated with 6 of the top 10 US sportsbooks.\"", sentiment: "positive", status: "recurring" },
    { title: "Operating leverage inflection", explanation: "Fixed cost base scaling with revenue; EBITDA margin +400bps.", evidence: "Adj EBITDA margin 20% vs 16% prior year.", sentiment: "positive", status: "new" },
    { title: "Free cash flow positive", explanation: "First quarter of sustained positive free cash flow.", evidence: "$18M FCF this quarter.", sentiment: "positive", status: "new" },
    { title: "Guidance raise", explanation: "FY revenue guide raised to $620M from $610M; EBITDA margin guide raised.", evidence: "Prepared remarks.", sentiment: "positive", status: "recurring" },
    { title: "European sportsbook headwinds", explanation: "Regulatory pressure in UK/DE modestly weighing on European growth.", evidence: "Europe revenue +6% vs Americas +38%.", sentiment: "negative", status: "recurring" },
    { title: "AI-driven product roadmap", explanation: "Computer vision + LLM products (BetVision, Second Spectrum) as differentiation.", evidence: "Multiple product SKUs referenced.", sentiment: "positive", status: "new" },
  ],
  narrative: {
    coreStory: "Sportsbook data + NFL exclusivity + AI-driven product = high-margin recurring revenue at scale.",
    growthDrivers: ["NFL BetVision", "Second Spectrum expansion", "Sportsbook ARPU"],
    profitabilityStory: "Operating leverage kicking in; guiding to 30%+ EBITDA margin by 2027.",
    strategicPriorities: ["US sportsbook penetration", "AI product moat", "FCF discipline"],
    confidenceLevel: "High",
    toneChange: "Notably more confident on FCF and margin trajectory.",
  },
  qa: {
    topConcerns: ["Contract renewal terms (leagues)", "European regulation", "Customer concentration"],
    pushedTopics: ["NFL contract economics", "BetVision revenue disclosure", "M&A appetite"],
    repeatedQuestions: ["When do we see 30% EBITDA margin?", "How sticky is BetVision?"],
    strongestAnswers: ["Operating leverage math", "NFL renewal path"],
    weakestAnswers: ["Specific BetVision ARR disclosure", "European regulatory sensitivity"],
  },
  bull: {
    mainArgument: "Cash-flow inflection with structural operating leverage on a durable data moat.",
    points: ["NFL exclusive rights", "FCF positive", "Guidance raise", "AI product differentiation"],
    catalysts: ["Additional league renewals", "US state legalization", "Margin expansion"],
    analystView: "9 analysts; average PT $12.60 implies ~34% upside.",
  },
  bear: {
    mainArgument: "League cost inflation + European regulation could compress the margin story.",
    points: ["Rising rights costs", "European regulatory headwinds", "Customer concentration in top sportsbooks"],
    risks: ["NFL renewal pricing", "New market regulation", "Competitive bidding on leagues"],
    analystView: "Bear PT $8 assumes rights costs step up materially.",
  },
  qoq: {
    increasing: ["BetVision", "FCF", "US sportsbook ARPU"],
    decreasing: ["Europe growth", "Media segment"],
    newThemes: ["FCF sustainability", "AI product moat"],
    droppedThemes: ["Losses guidance"],
    repeatedPhrases: ["\"Operating leverage\"", "\"BetVision\"", "\"NFL\""],
    kpiChanges: "Adj EBITDA margin 16% → 20%; FCF -$5M → +$18M.",
    guidanceChanges: "Revenue guide raised; EBITDA guide raised.",
    analystSentimentChange: "PTs raised across 6 shops; consensus moved to Buy.",
  },
  metrics: [
    { label: "Revenue", value: "$142M", change: "+24% YoY", sentiment: "positive" },
    { label: "Adjusted EBITDA", value: "$28.4M", change: "+58% YoY", sentiment: "positive" },
    { label: "Adj EBITDA Margin", value: "20.0%", change: "+400bps YoY", sentiment: "positive" },
    { label: "Free Cash Flow", value: "$18M", change: "vs -$5M YoY", sentiment: "positive" },
    { label: "Americas Revenue", value: "$82M", change: "+38% YoY", sentiment: "positive" },
    { label: "FY Revenue Guide", value: "$620M (raised)", change: "+$10M", sentiment: "positive" },
  ],
  quotes: [
    { speaker: "Mark Locke", role: "CEO", topic: "BetVision", quote: "BetVision is now integrated with 6 of the top 10 US sportsbooks.", whyItMatters: "Validates the flagship AI product's traction." },
    { speaker: "Nick Taylor", role: "CFO", topic: "FCF", quote: "We are decisively free-cash-flow positive.", whyItMatters: "Marks the profitability inflection." },
    { speaker: "Mark Locke", role: "CEO", topic: "NFL", quote: "The NFL relationship is deepening across every product line.", whyItMatters: "De-risks the largest contract in the business." },
  ],
  watchlist: [
    { category: "Metric", item: "Adjusted EBITDA margin trajectory to 30%" },
    { category: "Metric", item: "BetVision integration count" },
    { category: "Theme", item: "US state legalization" },
    { category: "Risk", item: "European regulatory changes" },
    { category: "Catalyst", item: "Next league rights renewal" },
  ],
};

const SRAD: EarningsAnalysis = {
  profile: {
    ticker: "SRAD",
    name: "Sportradar Group AG",
    sector: "Sports Tech / Data",
    marketCap: "$4.6B",
    price: 15.28,
    change: -0.12,
    changePct: -0.78,
    earningsDate: "2026-05-08",
    earningsQuarter: "Q1 2026",
  },
  priceTarget: { current: 15.28, average: 17.4, high: 22, low: 12, analysts: 11, rating: "Buy" },
  reaction: {
    oneDay: 2.4,
    fiveDay: 3.1,
    sinceEarnings: 4.7,
    reasonSummary:
      "Revenue beat with strong US growth. Managed Trading Services growth accelerated. Guidance reiterated.",
    marketReaction: "Modestly positive; investors want a guidance raise before re-rating.",
  },
  callSummary:
    "Sportradar delivered 23% revenue growth with US up 41%. MTS accelerated and management highlighted product roadmap with AI-driven trading and marketing services.",
  sentimentScore: 48,
  themes: [
    { title: "US momentum", explanation: "US segment growing 41% YoY as sportsbooks scale.", evidence: "US revenue $92M.", sentiment: "positive", status: "recurring" },
    { title: "Managed Trading Services scale", explanation: "MTS is highest-margin product line and accelerating.", evidence: "MTS revenue +34% YoY.", sentiment: "positive", status: "recurring" },
    { title: "AI-driven marketing services", explanation: "New AI marketing product being rolled out to sportsbooks.", evidence: "\"Early traction with top-5 US operator.\"", sentiment: "positive", status: "new" },
    { title: "NBA + ATP renewals", explanation: "Recent renewals reinforce rights moat but at higher cost.", evidence: "Cost of services +18% YoY.", sentiment: "neutral", status: "recurring" },
    { title: "Guidance conservative", explanation: "Guidance reiterated rather than raised; some investors wanted more.", evidence: "Prepared remarks.", sentiment: "negative", status: "new" },
  ],
  narrative: {
    coreStory: "Global sports data + AI-driven services with a durable rights moat.",
    growthDrivers: ["US sportsbook scale", "MTS", "AI marketing services"],
    profitabilityStory: "Margin expansion driven by MTS mix and operating leverage.",
    strategicPriorities: ["US expansion", "Product-led differentiation", "Rights portfolio management"],
    confidenceLevel: "Medium",
    toneChange: "Slightly more cautious framing on guidance.",
  },
  qa: {
    topConcerns: ["Rights cost inflation", "Guidance conservatism", "MTS unit economics"],
    pushedTopics: ["Guidance philosophy", "AI marketing revenue model", "Capital allocation"],
    repeatedQuestions: ["Why not raise guidance?", "How large is AI marketing TAM?"],
    strongestAnswers: ["MTS margin structure", "US customer roadmap"],
    weakestAnswers: ["Specific AI product ARR", "Rights renewal cost math"],
  },
  bull: {
    mainArgument: "Durable data moat + operating leverage as MTS scales.",
    points: ["US +41%", "MTS +34%", "Sticky sportsbook contracts", "AI product optionality"],
    catalysts: ["Guidance raise mid-year", "New product ARR disclosure", "Buyback"],
    analystView: "11 analysts; average PT $17.40 implies ~14% upside.",
  },
  bear: {
    mainArgument: "Rights inflation and conservative guidance limit near-term re-rating.",
    points: ["Rising rights costs", "Guidance conservatism", "FX headwinds"],
    risks: ["Rights renewal pricing", "Currency exposure", "Sportsbook consolidation"],
    analystView: "Bear PT $12 on rights cost pressure.",
  },
  qoq: {
    increasing: ["US momentum", "MTS", "AI marketing"],
    decreasing: ["European growth"],
    newThemes: ["AI marketing services"],
    droppedThemes: ["Media rights re-negotiation color"],
    repeatedPhrases: ["\"Managed Trading Services\"", "\"US momentum\""],
    kpiChanges: "MTS growth 28% → 34%; US growth 36% → 41%.",
    guidanceChanges: "Reiterated (not raised) — modest disappointment.",
    analystSentimentChange: "Unchanged to slightly positive.",
  },
  metrics: [
    { label: "Revenue", value: "$314M", change: "+23% YoY", sentiment: "positive" },
    { label: "US Revenue", value: "$92M", change: "+41% YoY", sentiment: "positive" },
    { label: "MTS Revenue", value: "$62M", change: "+34% YoY", sentiment: "positive" },
    { label: "Adj EBITDA", value: "$58M", change: "+29% YoY", sentiment: "positive" },
    { label: "Adj EBITDA Margin", value: "18.5%", change: "+80bps YoY", sentiment: "positive" },
    { label: "FY Guide", value: "$1.28B (reiterated)", change: "unchanged", sentiment: "neutral" },
  ],
  quotes: [
    { speaker: "Carsten Koerl", role: "CEO", topic: "US", quote: "The US remains our fastest-growing market.", whyItMatters: "Reinforces the core US thesis." },
    { speaker: "Gerard Griffin", role: "CFO", topic: "Margin", quote: "We are on track to expand adjusted EBITDA margin by 100bps this year.", whyItMatters: "Anchors the margin path." },
  ],
  watchlist: [
    { category: "Metric", item: "MTS growth rate" },
    { category: "Metric", item: "US take-rate expansion" },
    { category: "Theme", item: "AI marketing services ramp" },
    { category: "Risk", item: "Rights renewal costs" },
    { category: "Catalyst", item: "Mid-year guidance raise" },
  ],
};

const TTD: EarningsAnalysis = {
  profile: {
    ticker: "TTD",
    name: "The Trade Desk, Inc.",
    sector: "AdTech",
    marketCap: "$28.4B",
    price: 58.12,
    change: -3.42,
    changePct: -5.56,
    earningsDate: "2026-05-08",
    earningsQuarter: "Q1 2026",
  },
  priceTarget: { current: 58.12, average: 84.5, high: 120, low: 55, analysts: 32, rating: "Mixed" },
  reaction: {
    oneDay: -18.4,
    fiveDay: -22.1,
    sinceEarnings: -25.8,
    reasonSummary:
      "First revenue miss in company history. Kokai rollout execution issues cited. Guidance below consensus.",
    marketReaction: "Sharp negative — multiple downgrades. Bulls point to CTV secular story remaining intact.",
  },
  callSummary:
    "The Trade Desk missed revenue for the first time as a public company. Management attributed the miss to internal execution issues around the Kokai platform transition and reorganized go-to-market. Guidance was set below the Street.",
  sentimentScore: -42,
  themes: [
    { title: "Kokai transition friction", explanation: "Platform migration to Kokai created customer disruption and slower adoption than planned.", evidence: "\"We didn't execute at the level our clients expect.\"", sentiment: "negative", status: "new" },
    { title: "Go-to-market reorg", explanation: "Sales team restructured to address execution issues.", evidence: "New GTM leadership announced.", sentiment: "neutral", status: "new" },
    { title: "CTV strength continues", explanation: "CTV remains the primary secular driver even amid the miss.", evidence: "\"CTV is our largest and fastest-growing channel.\"", sentiment: "positive", status: "recurring" },
    { title: "Retail media / UID2 momentum", explanation: "Retail media and UID2 adoption progressing.", evidence: "Multiple retail partnerships cited.", sentiment: "positive", status: "recurring" },
    { title: "Guidance reset", explanation: "Q2 guide below consensus; FY implicit reset.", evidence: "Prepared remarks.", sentiment: "negative", status: "new" },
    { title: "Margin pressure", explanation: "Investment in platform + GTM weighs on near-term margin.", evidence: "Adj EBITDA margin guide -300bps YoY.", sentiment: "negative", status: "new" },
  ],
  narrative: {
    coreStory: "Independent DSP powering the open internet, with CTV and retail media as the future.",
    growthDrivers: ["CTV", "Retail media", "UID2 identity", "Kokai AI features"],
    profitabilityStory: "Near-term margin compression to invest in the recovery; long-term margin structure unchanged.",
    strategicPriorities: ["Kokai adoption", "GTM execution", "CTV / retail media leadership"],
    confidenceLevel: "Low",
    toneChange: "Notably humble — management took accountability, tone markedly less confident.",
  },
  qa: {
    topConcerns: ["Kokai timing", "Competitive share loss to Amazon DSP", "Guidance credibility"],
    pushedTopics: ["When does growth reaccelerate?", "Is this share loss or execution?", "Capital return plans"],
    repeatedQuestions: ["Kokai adoption %?", "What changed in the last 60 days?"],
    strongestAnswers: ["Long-term CTV thesis", "Kokai product roadmap"],
    weakestAnswers: ["Timeline to reacceleration", "Share loss quantification"],
  },
  bull: {
    mainArgument: "Rare execution stumble in a durable secular winner — attractive re-entry.",
    points: ["CTV secular tailwind intact", "Kokai long-term product story", "Balance sheet strength"],
    catalysts: ["Kokai adoption inflection", "Guidance beat next quarter", "GTM reorg pays off"],
    analystView: "32 analysts; average PT $84.50 implies ~45% upside — wide dispersion.",
  },
  bear: {
    mainArgument: "Amazon DSP is taking share and Kokai has broken the compounder thesis.",
    points: ["First-ever revenue miss", "Amazon DSP competitive pressure", "Guidance credibility damaged", "Margin compression"],
    risks: ["Continued share loss", "Further guidance cuts", "Kokai adoption stall"],
    analystView: "Bear PT $55 assumes share loss persists.",
  },
  qoq: {
    increasing: ["Kokai mentions", "GTM reorg language", "Humble tone"],
    decreasing: ["Confidence in guidance", "Growth rate commentary"],
    newThemes: ["Execution accountability", "GTM restructuring"],
    droppedThemes: ["\"Best quarter ever\" framing"],
    repeatedPhrases: ["\"Kokai\"", "\"Execution\"", "\"Accountability\""],
    kpiChanges: "Revenue growth 25% → 17%; margin -300bps.",
    guidanceChanges: "Q2 guide well below consensus.",
    analystSentimentChange: "Multiple downgrades; PT cuts across 18 shops.",
  },
  metrics: [
    { label: "Revenue", value: "$616M", change: "+17% YoY (miss)", sentiment: "negative" },
    { label: "Adj EBITDA", value: "$208M", change: "+8% YoY", sentiment: "negative" },
    { label: "Adj EBITDA Margin", value: "33.8%", change: "-280bps YoY", sentiment: "negative" },
    { label: "Free Cash Flow", value: "$210M", change: "+12% YoY", sentiment: "positive" },
    { label: "Q2 Revenue Guide", value: "$682M (below cons)", change: "-6% vs cons", sentiment: "negative" },
    { label: "Q2 EBITDA Guide", value: "$259M (below cons)", change: "-8% vs cons", sentiment: "negative" },
  ],
  quotes: [
    { speaker: "Jeff Green", role: "CEO", topic: "Accountability", quote: "We didn't execute at the level our clients expect.", whyItMatters: "Rare admission — sets a reset tone." },
    { speaker: "Jeff Green", role: "CEO", topic: "CTV", quote: "CTV is our largest and fastest-growing channel.", whyItMatters: "Anchors the intact long-term thesis." },
    { speaker: "Laura Schenkein", role: "CFO", topic: "Margin", quote: "We are investing to reaccelerate growth.", whyItMatters: "Signals near-term margin pressure is intentional." },
    { speaker: "Shyam Patil", role: "Susquehanna Analyst", topic: "Share", quote: "How much of this is Amazon DSP?", whyItMatters: "Frames the central bear question." },
  ],
  watchlist: [
    { category: "Metric", item: "Q2 revenue vs the reset guide" },
    { category: "Metric", item: "Kokai adoption %" },
    { category: "Theme", item: "GTM reorg execution" },
    { category: "Risk", item: "Amazon DSP competitive share" },
    { category: "Question", item: "When does growth reaccelerate?" },
    { category: "Catalyst", item: "First quarter of Kokai-driven upside" },
  ],
};

const REGISTRY: Record<string, EarningsAnalysis> = { NVDA, AAPL, GENI, SRAD, TTD };

export function getMockAnalysis(ticker: string): EarningsAnalysis | null {
  return REGISTRY[ticker.toUpperCase()] ?? null;
}

export function getSupportedTickers(): { ticker: string; name: string; sector: string }[] {
  return Object.values(REGISTRY).map((a) => ({
    ticker: a.profile.ticker,
    name: a.profile.name,
    sector: a.profile.sector,
  }));
}
